micronaut:
  application:
    name: bnext

datasources:
  default:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    dialect: MYSQL

jpa:
  default:
    packages-to-scan:
      - 'com.assessment.entities'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true